//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KichikuBili {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_Hans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_Hans() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KichikuBili.Resource.zh_Hans", typeof(Resource_zh_Hans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于(A) 的本地化字符串。
        /// </summary>
        internal static string AboutStr {
            get {
                return ResourceManager.GetString("AboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览... 的本地化字符串。
        /// </summary>
        internal static string BrowseStr {
            get {
                return ResourceManager.GetString("BrowseStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copyingstr {
            get {
                return ResourceManager.GetString("Copyingstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string CopyStr {
            get {
                return ResourceManager.GetString("CopyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前路径不存在，是否创建目录 的本地化字符串。
        /// </summary>
        internal static string Currpathstr {
            get {
                return ResourceManager.GetString("Currpathstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径不能为空! 的本地化字符串。
        /// </summary>
        internal static string Emptypathstr {
            get {
                return ResourceManager.GetString("Emptypathstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前集数名称不合法，请重命名为: 的本地化字符串。
        /// </summary>
        internal static string Epistr {
            get {
                return ResourceManager.GetString("Epistr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始导出 的本地化字符串。
        /// </summary>
        internal static string ExecuteStr {
            get {
                return ResourceManager.GetString("ExecuteStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(X) 的本地化字符串。
        /// </summary>
        internal static string ExitStr {
            get {
                return ResourceManager.GetString("ExitStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开失败:  的本地化字符串。
        /// </summary>
        internal static string Failtoopenstr {
            get {
                return ResourceManager.GetString("Failtoopenstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(F) 的本地化字符串。
        /// </summary>
        internal static string FileStr {
            get {
                return ResourceManager.GetString("FileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部完成 的本地化字符串。
        /// </summary>
        internal static string Finishstr {
            get {
                return ResourceManager.GetString("Finishstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已找到 的本地化字符串。
        /// </summary>
        internal static string Foundstr {
            get {
                return ResourceManager.GetString("Foundstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已处理 的本地化字符串。
        /// </summary>
        internal static string Handlestr {
            get {
                return ResourceManager.GetString("Handlestr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(H) 的本地化字符串。
        /// </summary>
        internal static string HelpStr {
            get {
                return ResourceManager.GetString("HelpStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入目录: 的本地化字符串。
        /// </summary>
        internal static string InputPathStr {
            get {
                return ResourceManager.GetString("InputPathStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名不合法! 的本地化字符串。
        /// </summary>
        internal static string Invastr {
            get {
                return ResourceManager.GetString("Invastr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入路径不合法! 的本地化字符串。
        /// </summary>
        internal static string Noexistpathstr {
            get {
                return ResourceManager.GetString("Noexistpathstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名不合法 的本地化字符串。
        /// </summary>
        internal static string Nproperstr {
            get {
                return ResourceManager.GetString("Nproperstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出目录 的本地化字符串。
        /// </summary>
        internal static string Optpath {
            get {
                return ResourceManager.GetString("Optpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出目录: 的本地化字符串。
        /// </summary>
        internal static string OutputPathStr {
            get {
                return ResourceManager.GetString("OutputPathStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 的本地化字符串。
        /// </summary>
        internal static string OutputStr {
            get {
                return ResourceManager.GetString("OutputStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标文件夹 的本地化字符串。
        /// </summary>
        internal static string Selectstr {
            get {
                return ResourceManager.GetString("Selectstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已跳过 的本地化字符串。
        /// </summary>
        internal static string Skipstr {
            get {
                return ResourceManager.GetString("Skipstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string StartStr {
            get {
                return ResourceManager.GetString("StartStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入路径文件结构不合法! 的本地化字符串。
        /// </summary>
        internal static string Structstr {
            get {
                return ResourceManager.GetString("Structstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前视频名称不合法，请重命名为:  的本地化字符串。
        /// </summary>
        internal static string Vidstr {
            get {
                return ResourceManager.GetString("Vidstr", resourceCulture);
            }
        }
    }
}
